// Open pool: questions that are never scheduled as dailies. They feed Nets, duels, live 1v1, Match Day and
// Test Match editions. Same rules as the bank: a source for every fact, human fact-check before going live.
import type { Q } from "./questions";

const W = (s: string) => `https://en.wikipedia.org/wiki/${s}`;

export const POOL: Q[] = [
  { id: "lara-501", region: "global", text: "Brian Lara made 501 not out for Warwickshire, the highest score in first-class cricket, at this ground.", answer: "Edgbaston, Birmingham", when: "June 1994", lat: 52.4559, lng: -1.9025, scaleKm: 500, story: "Lara did it seven weeks after his Test-record 375, against Durham.", source: W("Brian_Lara") },
  { id: "laker-19", region: "global", text: "Jim Laker took 19 wickets in a Test against Australia at this ground.", answer: "Old Trafford, Manchester", when: "July 1956", lat: 53.4568, lng: -2.2869, scaleKm: 500, story: "Laker took 9 for 37 and 10 for 53. No bowler has taken more than 17 in any other Test.", source: W("Jim_Laker") },
  { id: "hanif-337", region: "global", text: "Hanif Mohammad batted for more than 16 hours to make 337 and save a Test on this Caribbean island.", answer: "Kensington Oval, Bridgetown, Barbados", when: "January 1958", lat: 13.1044, lng: -59.6211, scaleKm: 600, story: "Pakistan followed on 473 behind. Hanif's 970-minute innings is still the longest in Test cricket.", source: W("Hanif_Mohammad") },
  { id: "sobers-six-sixes", region: "global", text: "Garfield Sobers became the first player to hit six sixes in a first-class over at this ground.", answer: "St Helen's, Swansea", when: "31 August 1968", lat: 51.6138, lng: -3.966, scaleKm: 500, story: "Batting for Nottinghamshire, Sobers took all six balls of Malcolm Nash's over into the stands.", source: W("Garfield_Sobers") },
  { id: "gibbs-six-sixes", region: "global", text: "Herschelle Gibbs hit six sixes in an over against the Netherlands at a World Cup match on this island.", answer: "Warner Park, Basseterre, St Kitts", when: "March 2007", lat: 17.3, lng: -62.7222, scaleKm: 600, story: "It was the first time anyone had hit six sixes in an over in an ODI.", source: W("Herschelle_Gibbs") },
  { id: "sachin-100th-100", region: "global", text: "Sachin Tendulkar scored his 100th international century against Bangladesh in this city.", answer: "Sher-e-Bangla Stadium, Mirpur, Dhaka", when: "March 2012", lat: 23.8069, lng: 90.3634, scaleKm: 600, story: "It came a year after his 99th. No one else has reached even 80 international hundreds.", source: W("Sachin_Tendulkar") },
  { id: "rohit-264", region: "india", text: "Rohit Sharma made 264, the highest score in men's ODIs, against Sri Lanka at this ground.", answer: "Eden Gardens, Kolkata", when: "November 2014", lat: 22.5646, lng: 88.3433, scaleKm: 400, story: "Rohit hit 33 fours and 9 sixes off 173 balls.", source: W("Rohit_Sharma") },
  { id: "sehwag-309", region: "global", text: "Virender Sehwag became India's first Test triple centurion in this Pakistani city.", answer: "Multan", when: "March 2004", lat: 30.1575, lng: 71.5249, scaleKm: 500, story: "The innings earned him the nickname \"Sultan of Multan\".", source: W("Virender_Sehwag") },
  { id: "kapil-175", region: "global", text: "Kapil Dev rescued India from 17 for 5 with 175 not out against Zimbabwe at this small English ground.", answer: "Nevill Ground, Tunbridge Wells", when: "18 June 1983", lat: 51.125, lng: 0.264, scaleKm: 500, story: "The BBC was on strike that day, so no footage of the innings exists. India went on to win the World Cup.", source: W("Kapil_Dev") },
  { id: "dhoni-183", region: "india", text: "MS Dhoni made 183 not out against Sri Lanka, then a record for a wicketkeeper in ODIs, in this city.", answer: "Sawai Mansingh Stadium, Jaipur", when: "October 2005", lat: 26.8943, lng: 75.8032, scaleKm: 400, story: "Dhoni hit 10 sixes as India chased 299 with more than 3 overs to spare.", source: W("MS_Dhoni") },
  { id: "india-first-test-win", region: "india", text: "India won their first-ever Test match, against England, at this ground.", answer: "MA Chidambaram Stadium, Chennai", when: "February 1952", lat: 13.0628, lng: 80.2793, scaleKm: 400, story: "Vinoo Mankad took 12 wickets as India won by an innings, 20 years after their first Test.", source: W("MA_Chidambaram_Stadium") },
  { id: "t20wc-2007-final", region: "global", text: "India beat Pakistan in the first T20 World Cup final at this ground.", answer: "The Wanderers, Johannesburg", when: "24 September 2007", lat: -26.1319, lng: 28.0572, scaleKm: 700, story: "Misbah-ul-Haq's scoop off Joginder Sharma was caught by Sreesanth at short fine leg.", source: W("2007_ICC_World_Twenty20_final") },
  { id: "wc-2011-semi-mohali", region: "india", text: "India beat Pakistan in the 2011 World Cup semi-final, watched by both prime ministers, in this city.", answer: "PCA Stadium, Mohali", when: "30 March 2011", lat: 30.6909, lng: 76.7375, scaleKm: 400, story: "Sachin Tendulkar top-scored with 85 as India won by 29 runs.", source: W("2011_Cricket_World_Cup") },
  { id: "wc-2003-final", region: "global", text: "Ricky Ponting's 140 not out won Australia the 2003 World Cup final at this ground.", answer: "The Wanderers, Johannesburg", when: "23 March 2003", lat: -26.1319, lng: 28.0572, scaleKm: 700, story: "Australia made 359 for 2 and beat India by 125 runs.", source: W("2003_Cricket_World_Cup_final") },
  { id: "wc-1996-final", region: "global", text: "Aravinda de Silva's hundred won Sri Lanka the 1996 World Cup final in this city.", answer: "Gaddafi Stadium, Lahore", when: "17 March 1996", lat: 31.5134, lng: 74.3336, scaleKm: 500, story: "It was the first World Cup final played under lights. Sri Lanka beat Australia by seven wickets.", source: W("1996_Cricket_World_Cup_final") },
  { id: "wc-1992-final", region: "global", text: "Imran Khan's Pakistan won the 1992 World Cup final against England at this ground.", answer: "Melbourne Cricket Ground", when: "25 March 1992", lat: -37.82, lng: 144.9834, scaleKm: 700, story: "Wasim Akram took two wickets in two balls to break England's chase.", source: W("1992_Cricket_World_Cup_final") },
  { id: "wc-1975-final", region: "global", text: "Clive Lloyd's hundred won the West Indies the first-ever World Cup final at this ground.", answer: "Lord's, London", when: "21 June 1975", lat: 51.5294, lng: -0.1727, scaleKm: 500, story: "Viv Richards ran out three Australians in the field.", source: W("1975_Cricket_World_Cup_final") },
  { id: "gayle-175", region: "india", text: "Chris Gayle smashed 175 not out, the highest score in T20 cricket, in an IPL game at this ground.", answer: "M. Chinnaswamy Stadium, Bengaluru", when: "23 April 2013", lat: 12.9788, lng: 77.5996, scaleKm: 400, story: "Gayle reached his hundred in 30 balls and hit 17 sixes against Pune Warriors.", source: W("Chris_Gayle") },
  { id: "afghanistan-first-test-win", region: "india", text: "Afghanistan won their first Test match, against Ireland, in this Indian city.", answer: "Dehradun", when: "March 2019", lat: 30.3165, lng: 78.0322, scaleKm: 400, story: "Afghanistan played their home games in India at the time. They won by seven wickets in only their second Test.", source: W("Afghanistan_national_cricket_team") },
  { id: "obrien-50-ball-100", region: "india", text: "Kevin O'Brien hit a 50-ball hundred as Ireland stunned England at the 2011 World Cup in this city.", answer: "M. Chinnaswamy Stadium, Bengaluru", when: "2 March 2011", lat: 12.9788, lng: 77.5996, scaleKm: 400, story: "Ireland chased 328, then the highest successful chase in World Cup history.", source: W("Kevin_O%27Brien_(cricketer)") },
  { id: "sachin-test-debut", region: "global", text: "A 16-year-old Sachin Tendulkar made his Test debut against Pakistan in this city.", answer: "National Stadium, Karachi", when: "November 1989", lat: 24.8964, lng: 67.0817, scaleKm: 500, story: "He faced Wasim Akram and Waqar Younis, who was also making his debut, and made 15.", source: W("Sachin_Tendulkar") },
  { id: "murali-birthplace", region: "global", text: "Muttiah Muralitharan, Test cricket's leading wicket-taker, was born in this Sri Lankan hill city.", answer: "Kandy", when: "17 April 1972", lat: 7.2906, lng: 80.6337, scaleKm: 500, story: "His family ran a biscuit business in Kandy.", source: W("Muttiah_Muralitharan") },
  { id: "sangakkara-birthplace", region: "global", text: "Kumar Sangakkara was born in this town in Sri Lanka's Central Province.", answer: "Matale", when: "27 October 1977", lat: 7.4675, lng: 80.6234, scaleKm: 500, story: "Sangakkara scored more than 28,000 international runs and later became MCC president.", source: W("Kumar_Sangakkara") },
  { id: "williamson-birthplace", region: "global", text: "Kane Williamson was born in this city on New Zealand's North Island.", answer: "Tauranga", when: "8 August 1990", lat: -37.6878, lng: 176.1651, scaleKm: 600, story: "Williamson captained New Zealand to the first World Test Championship title in 2021.", source: W("Kane_Williamson") },
  { id: "abd-birthplace", region: "global", text: "AB de Villiers was born in this South African city, the country's administrative capital.", answer: "Pretoria", when: "17 February 1984", lat: -25.7479, lng: 28.2293, scaleKm: 600, story: "De Villiers played 114 Tests for South Africa and later starred for Bengaluru in the IPL.", source: W("AB_de_Villiers") },
  { id: "root-birthplace", region: "global", text: "Joe Root, England's leading Test run-scorer, was born in this Yorkshire city.", answer: "Sheffield", when: "30 December 1990", lat: 53.3811, lng: -1.4701, scaleKm: 500, story: "Root came through Sheffield Collegiate, the same club as Michael Vaughan.", source: W("Joe_Root") },
  { id: "smith-birthplace", region: "global", text: "Steve Smith was born in this city and plays his domestic cricket for its state, New South Wales.", answer: "Sydney", when: "2 June 1989", lat: -33.8688, lng: 151.2093, scaleKm: 700, story: "Smith was first picked for Australia as a leg-spinner who batted at number eight.", source: W("Steve_Smith_(cricketer)") },
  { id: "babar-birthplace", region: "global", text: "Babar Azam was born in this city, where he once worked as a ball boy at international matches.", answer: "Lahore", when: "15 October 1994", lat: 31.5204, lng: 74.3587, scaleKm: 500, story: "His cousins Kamran and Umar Akmal also played for Pakistan.", source: W("Babar_Azam") },
  { id: "shakib-birthplace", region: "global", text: "Shakib Al Hasan, Bangladesh's great all-rounder, was born in this district town.", answer: "Magura", when: "24 March 1987", lat: 23.4873, lng: 89.4197, scaleKm: 500, story: "Shakib was the first player to be ranked the world's top all-rounder in all three formats at once.", source: W("Shakib_Al_Hasan") },
  { id: "harmanpreet-171", region: "global", text: "Harmanpreet Kaur made 171 not out against Australia in the 2017 Women's World Cup semi-final at this ground.", answer: "County Ground, Derby", when: "20 July 2017", lat: 52.929, lng: -1.463, scaleKm: 500, story: "She reached 171 off 115 balls in a game cut to 42 overs a side.", source: W("Harmanpreet_Kaur") },
  { id: "mandhana-sangli", region: "india", text: "Smriti Mandhana grew up and learned her cricket in this Maharashtra town.", answer: "Sangli", when: "1990s–2000s", lat: 16.8524, lng: 74.5815, scaleKm: 400, story: "Mandhana was born in Mumbai but moved to Sangli as a child, where her brother also played.", source: W("Smriti_Mandhana") },
  { id: "jhulan-birthplace", region: "india", text: "Jhulan Goswami, known as the \"Chakdaha Express\", was born in this West Bengal town.", answer: "Chakdaha", when: "25 November 1982", lat: 23.0833, lng: 88.5167, scaleKm: 400, story: "She retired as the leading wicket-taker in women's ODIs.", source: W("Jhulan_Goswami") },
  { id: "abd-31-ball-100", region: "global", text: "AB de Villiers hit the fastest ODI hundred, in 31 balls, against the West Indies at this ground.", answer: "The Wanderers, Johannesburg", when: "18 January 2015", lat: -26.1319, lng: 28.0572, scaleKm: 700, story: "He went on to 149 off 44 balls, with 16 sixes.", source: W("AB_de_Villiers") },
  { id: "afridi-37-ball-100", region: "global", text: "A teenage Shahid Afridi hit a 37-ball ODI hundred against Sri Lanka in this African city.", answer: "Nairobi Gymkhana Club Ground", when: "October 1996", lat: -1.269, lng: 36.81, scaleKm: 700, story: "It was his first international innings with the bat. The record stood for more than 17 years.", source: W("Shahid_Afridi") },
  { id: "brathwaite-four-sixes", region: "india", text: "Carlos Brathwaite hit four sixes in a row off Ben Stokes to win the 2016 T20 World Cup final here.", answer: "Eden Gardens, Kolkata", when: "3 April 2016", lat: 22.5646, lng: 88.3433, scaleKm: 400, story: "The West Indies needed 19 off the last over. Commentator Ian Bishop: \"Carlos Brathwaite! Remember the name!\"", source: W("2016_ICC_World_Twenty20_final") },
  { id: "gilchrist-149", region: "global", text: "Adam Gilchrist hit 149, with a squash ball in his glove, in the 2007 World Cup final on this island.", answer: "Kensington Oval, Bridgetown, Barbados", when: "28 April 2007", lat: 13.1044, lng: -59.6211, scaleKm: 600, story: "Australia won their third World Cup in a row.", source: W("2007_Cricket_World_Cup_final") },
  { id: "kohli-odi-debut", region: "global", text: "Virat Kohli made his ODI debut against Sri Lanka at this ground built beside an ancient rock temple.", answer: "Rangiri Dambulla Stadium, Dambulla", when: "18 August 2008", lat: 7.86, lng: 80.65, scaleKm: 500, story: "Kohli made 12 opening the batting. He was 19 and had just won the Under-19 World Cup.", source: W("Virat_Kohli") },
  { id: "kenya-2003-semi", region: "global", text: "Kenya's fairytale run to the 2003 World Cup semi-final ended against India at this ground.", answer: "Kingsmead, Durban", when: "20 March 2003", lat: -29.8494, lng: 31.0292, scaleKm: 700, story: "Kenya remain the only associate nation to reach a men's World Cup semi-final.", source: W("2003_Cricket_World_Cup") },
  { id: "perry-birthplace", region: "global", text: "Ellyse Perry, who played football and cricket for Australia, was born in this city.", answer: "Sydney", when: "3 November 1990", lat: -33.8688, lng: 151.2093, scaleKm: 700, story: "Perry played in both a football World Cup and a cricket World Cup before she turned 21.", source: W("Ellyse_Perry") },
  { id: "tendulkar-200-test-last", region: "india", text: "Sachin Tendulkar played his 200th and final Test at his home ground in this city.", answer: "Wankhede Stadium, Mumbai", when: "November 2013", lat: 18.9389, lng: 72.8258, scaleKm: 400, story: "He made 74 against the West Indies, then gave a farewell speech the crowd still quotes.", source: W("Sachin_Tendulkar") },
];

// Editions: special rounds with their own leaderboard and a playable window (IST).
// Match Day editions (a round tied to a real fixture). Paused: the placeholder was removed and the automated version
// (fixtures feed → questions about the two teams and the ground, open that day only) isn't built yet.
export const MATCH_DAYS: { key: string; title: string; questionIds: string[]; opens: string; closes: string }[] = [];

/** Weekend Test Match: 10 balls, Saturday 00:00 to Sunday 23:59 IST. Multipliers build to a big final session. */
export const TEST_MULTS = [1, 1, 1, 1, 2, 2, 2, 3, 3, 3];
