// Question bank. Every fact needs a source link and a human fact-check before it goes live.
// scaleKm: smaller = precision matters more (~400 for Indian venues, 500-700 abroad).

export type Q = {
  id: string; text: string; answer: string; when: string;
  lat: number; lng: number; scaleKm: number; story: string; source: string; region: "india" | "global";
};

const W = (s: string) => `https://en.wikipedia.org/wiki/${s}`;

export const BANK: Q[] = [
  { id: "dhoni-2011-winning-six", region: "india", text: "MS Dhoni finished the 2011 World Cup final with a six into the stands at this ground.", answer: "Wankhede Stadium, Mumbai", when: "2 April 2011", lat: 18.9389, lng: 72.8258, scaleKm: 400, story: "Dhoni's 91 not out off 79 balls sealed India's first World Cup title in 28 years.", source: W("2011_Cricket_World_Cup_final") },
  { id: "mccullum-first-ipl-match", region: "india", text: "Brendon McCullum smashed 158* here in the very first match the IPL ever played.", answer: "M. Chinnaswamy Stadium, Bengaluru", when: "18 April 2008", lat: 12.9788, lng: 77.5996, scaleKm: 400, story: "McCullum's 158* off 73 balls for Kolkata against Bangalore launched the league with a bang.", source: W("2008_Indian_Premier_League") },
  { id: "bumrah-birthplace", region: "india", text: "Jasprit Bumrah was born in this city, now home to the biggest cricket stadium on Earth.", answer: "Ahmedabad", when: "6 December 1993", lat: 23.0225, lng: 72.5714, scaleKm: 400, story: "Bumrah grew up here. The city's Narendra Modi Stadium holds around 132,000 fans.", source: W("Jasprit_Bumrah") },
  { id: "warne-ball-of-the-century", region: "global", text: "With his first ball in Ashes cricket, Shane Warne bowled Mike Gatting with the \"Ball of the Century\" at this ground.", answer: "Old Trafford, Manchester", when: "4 June 1993", lat: 53.4568, lng: -2.2869, scaleKm: 500, story: "The leg-break drifted outside leg stump, pitched, spun past the bat and clipped the top of off.", source: W("Ball_of_the_Century") },
  { id: "yuvraj-six-sixes", region: "global", text: "Yuvraj Singh hit Stuart Broad for six sixes in an over at this ground.", answer: "Kingsmead, Durban", when: "19 September 2007", lat: -29.8494, lng: 31.0292, scaleKm: 700, story: "Yuvraj reached fifty in 12 balls at the first T20 World Cup, which India went on to win.", source: W("Yuvraj_Singh") },

  { id: "kapil-1983-final", region: "global", text: "Kapil Dev's India shocked the West Indies to win their first World Cup at this ground.", answer: "Lord's, London", when: "25 June 1983", lat: 51.5294, lng: -0.1727, scaleKm: 500, story: "India defended just 183. Kapil's running catch to remove Viv Richards turned the final.", source: W("1983_Cricket_World_Cup_final") },
  { id: "dhoni-birthplace", region: "india", text: "MS Dhoni was born in this city, which now has a stadium named after its state, Jharkhand.", answer: "Ranchi", when: "7 July 1981", lat: 23.3441, lng: 85.3096, scaleKm: 400, story: "Dhoni played football as a goalkeeper at school before a coach pushed him behind the stumps.", source: W("MS_Dhoni") },
  { id: "laxman-281", region: "india", text: "VVS Laxman made 281 here after India were made to follow on, ending Australia's 16-Test winning streak.", answer: "Eden Gardens, Kolkata", when: "March 2001", lat: 22.5646, lng: 88.3433, scaleKm: 400, story: "Laxman and Dravid batted through the whole fourth day. Harbhajan Singh then took 13 wickets in the match, including a hat-trick.", source: W("VVS_Laxman") },
  { id: "lara-400", region: "global", text: "Brian Lara became the only man to score 400 in a Test innings on this Caribbean island.", answer: "Antigua Recreation Ground, St John's", when: "April 2004", lat: 17.1204, lng: -61.8438, scaleKm: 600, story: "Lara took back the record from Matthew Hayden, 10 years after scoring 375 at the same ground.", source: W("Brian_Lara") },
  { id: "stokes-headingley", region: "global", text: "Ben Stokes hit 135 not out to win an Ashes Test by one wicket at this ground.", answer: "Headingley, Leeds", when: "25 August 2019", lat: 53.8176, lng: -1.5822, scaleKm: 500, story: "England needed 73 when the last man, Jack Leach, walked out. Leach made 1 not out.", source: W("Ben_Stokes") },

  { id: "kumble-10-wickets", region: "india", text: "Anil Kumble took all 10 Pakistan wickets in an innings at this ground.", answer: "Feroz Shah Kotla, Delhi", when: "February 1999", lat: 28.6379, lng: 77.2432, scaleKm: 400, story: "Kumble finished with 10 for 74, only the second bowler ever to take all ten in a Test innings.", source: W("Anil_Kumble") },
  { id: "kohli-birthplace", region: "india", text: "Virat Kohli was born in this city and played his early cricket for its state team.", answer: "Delhi", when: "5 November 1988", lat: 28.6139, lng: 77.209, scaleKm: 400, story: "Kohli batted for Delhi the day after his father died in 2006, then went to the funeral.", source: W("Virat_Kohli") },
  { id: "sachin-first-odi-200", region: "india", text: "Sachin Tendulkar scored the first double hundred in men's ODI history in this central Indian city.", answer: "Captain Roop Singh Stadium, Gwalior", when: "24 February 2010", lat: 26.2183, lng: 78.1828, scaleKm: 400, story: "Sachin made 200 not out against South Africa, reaching the milestone in the final over.", source: W("Sachin_Tendulkar") },
  { id: "first-ever-test", region: "global", text: "The first Test match ever played took place at this ground.", answer: "Melbourne Cricket Ground", when: "March 1877", lat: -37.82, lng: 144.9834, scaleKm: 700, story: "Australia beat England by 45 runs. The centenary Test in 1977 ended with the exact same margin.", source: W("Melbourne_Cricket_Ground") },
  { id: "the-438-game", region: "global", text: "South Africa chased down Australia's 434 in the \"438 game\" at this ground.", answer: "The Wanderers, Johannesburg", when: "12 March 2006", lat: -26.1319, lng: 28.0572, scaleKm: 700, story: "Herschelle Gibbs made 175 and South Africa won with one ball to spare.", source: W("438_ODI") },

  { id: "sachin-desert-storm", region: "global", text: "Sachin Tendulkar's \"Desert Storm\" innings against Australia happened at this ground, in the middle of a real sandstorm.", answer: "Sharjah Cricket Stadium", when: "22 April 1998", lat: 25.3322, lng: 55.4224, scaleKm: 600, story: "Play stopped for a sandstorm. Sachin then hit 143 to take India into the final on run rate.", source: W("Sharjah_Cricket_Stadium") },
  { id: "shoaib-birthplace", region: "global", text: "Shoaib Akhtar's nickname comes from the city where he was born.", answer: "Rawalpindi", when: "13 August 1975", lat: 33.5984, lng: 73.0441, scaleKm: 500, story: "The \"Rawalpindi Express\" was the first bowler officially timed above 100 mph, in 2003.", source: W("Shoaib_Akhtar") },
  { id: "murali-800", region: "global", text: "Muttiah Muralitharan took his 800th and final Test wicket with his last ball in Tests at this ground.", answer: "Galle International Stadium", when: "22 July 2010", lat: 6.03, lng: 80.215, scaleKm: 600, story: "Pragyan Ojha was the 800th victim, caught at slip. No one else has reached 800.", source: W("Muttiah_Muralitharan") },
  { id: "india-36-all-out", region: "global", text: "India were bowled out for 36, their lowest Test total, at this ground.", answer: "Adelaide Oval", when: "19 December 2020", lat: -34.9156, lng: 138.5961, scaleKm: 700, story: "No batter reached double figures. India came back to win the series 2-1.", source: W("Adelaide_Oval") },
  { id: "gabba-2021", region: "global", text: "Rishabh Pant's 89 not out ended Australia's 32-year unbeaten Test run at this ground.", answer: "The Gabba, Brisbane", when: "19 January 2021", lat: -27.4858, lng: 153.0381, scaleKm: 700, story: "A second-string Indian side chased 328 on the final day to win the series 2-1.", source: W("The_Gabba") },

  { id: "t20wc-2024-final", region: "global", text: "India won the 2024 T20 World Cup final on this Caribbean island.", answer: "Kensington Oval, Bridgetown, Barbados", when: "29 June 2024", lat: 13.1044, lng: -59.6211, scaleKm: 600, story: "Suryakumar Yadav's boundary catch off David Miller in the last over sealed a seven-run win over South Africa.", source: W("2024_ICC_Men%27s_T20_World_Cup_final") },
  { id: "wc-2023-final", region: "india", text: "Travis Head's 137 won Australia the 2023 World Cup final in front of about 90,000 fans in this city.", answer: "Narendra Modi Stadium, Ahmedabad", when: "19 November 2023", lat: 23.0916, lng: 72.5976, scaleKm: 400, story: "India had won all 10 games to reach the final. Australia lifted their sixth title.", source: W("2023_Cricket_World_Cup_final") },
  { id: "bradman-bowral", region: "global", text: "Don Bradman grew up in this small New South Wales town, now home to the Bradman Museum.", answer: "Bowral", when: "1910s", lat: -34.4778, lng: 150.418, scaleKm: 700, story: "Young Don practised by hitting a golf ball against a water tank with a single stump.", source: W("Bowral") },
  { id: "mccullum-302", region: "global", text: "Brendon McCullum made New Zealand's first Test triple century against India at this ground.", answer: "Basin Reserve, Wellington", when: "February 2014", lat: -41.3, lng: 174.7797, scaleKm: 700, story: "McCullum batted for nearly 13 hours to save the Test after New Zealand trailed by 246.", source: W("Basin_Reserve") },
  { id: "tied-test-1986", region: "india", text: "India and Australia played only the second tied Test in history at this ground.", answer: "MA Chidambaram Stadium, Chennai", when: "September 1986", lat: 13.0628, lng: 80.2793, scaleKm: 400, story: "Dean Jones batted through heat and sickness for 210. Maninder Singh was the last man out, lbw.", source: W("MA_Chidambaram_Stadium") },

  { id: "eng-481", region: "global", text: "England made 481 for 6 against Australia, then the highest ODI total, at this ground.", answer: "Trent Bridge, Nottingham", when: "19 June 2018", lat: 52.937, lng: -1.1322, scaleKm: 500, story: "Alex Hales hit 147 and Jonny Bairstow 139 as England beat Australia by 242 runs.", source: W("Trent_Bridge") },
  { id: "india-women-wc-2025", region: "india", text: "India's women won their first World Cup at this ground near Mumbai.", answer: "DY Patil Stadium, Navi Mumbai", when: "2 November 2025", lat: 19.0425, lng: 73.029, scaleKm: 400, story: "India beat South Africa by 52 runs in the final of the Women's ODI World Cup.", source: W("2025_Women%27s_Cricket_World_Cup_final") },
  { id: "mithali-birthplace", region: "india", text: "Mithali Raj, the highest run-scorer in women's international cricket, was born in this Rajasthan city.", answer: "Jodhpur", when: "3 December 1982", lat: 26.2389, lng: 73.0243, scaleKm: 400, story: "Mithali played more than two decades for India and captained them in two World Cup finals.", source: W("Mithali_Raj") },
  { id: "wc-1999-semi-tie", region: "global", text: "Allan Donald's run-out ended the tied 1999 World Cup semi-final between Australia and South Africa at this ground.", answer: "Edgbaston, Birmingham", when: "17 June 1999", lat: 52.4559, lng: -1.9025, scaleKm: 500, story: "Australia went through on a better Super Six record and won the final three days later.", source: W("Edgbaston_Cricket_Ground") },
  { id: "sachin-98-centurion", region: "global", text: "Sachin Tendulkar's 98 against Pakistan at the 2003 World Cup, including an upper-cut six off Shoaib, came at this ground.", answer: "SuperSport Park, Centurion", when: "1 March 2003", lat: -25.8603, lng: 28.1797, scaleKm: 700, story: "Chasing 274, India won by six wickets. Sachin's 98 came off 75 balls.", source: W("SuperSport_Park") },
  { id: "sl-952", region: "global", text: "Sri Lanka made 952 for 6, the highest Test total ever, against India at this ground.", answer: "R. Premadasa Stadium, Colombo", when: "August 1997", lat: 6.9398, lng: 79.8719, scaleKm: 600, story: "Sanath Jayasuriya made 340 and Roshan Mahanama 225 in a record partnership of 576.", source: W("R._Premadasa_Stadium") },
  { id: "wasim-birthplace", region: "global", text: "Wasim Akram, the \"Sultan of Swing\", was born in this city, Pakistan's cricket capital.", answer: "Lahore", when: "3 June 1966", lat: 31.5204, lng: 74.3587, scaleKm: 500, story: "Wasim took 916 international wickets and won the 1992 World Cup final's Player of the Match award.", source: W("Wasim_Akram") },
  { id: "sachin-birthplace", region: "india", text: "Sachin Tendulkar was born in this city and learned his cricket at Shivaji Park.", answer: "Mumbai", when: "24 April 1973", lat: 19.076, lng: 72.8777, scaleKm: 400, story: "Coach Ramakant Achrekar put a coin on the stumps. Anyone who got Sachin out won it.", source: W("Sachin_Tendulkar") },
  { id: "rashid-birthplace", region: "global", text: "Rashid Khan, Afghanistan's leg-spin superstar, was born in this eastern province.", answer: "Nangarhar, Afghanistan", when: "20 September 1998", lat: 34.43, lng: 70.45, scaleKm: 600, story: "Rashid learned the game in refugee camps in Pakistan and became a T20 star in leagues worldwide.", source: W("Rashid_Khan") },
  { id: "wc-2019-final", region: "global", text: "England won the 2019 World Cup final on boundary count after a tied Super Over at this ground.", answer: "Lord's, London", when: "14 July 2019", lat: 51.5294, lng: -0.1727, scaleKm: 500, story: "Ben Stokes made 84 not out. England and New Zealand were level after 50 overs and after the Super Over.", source: W("2019_Cricket_World_Cup_final") },
  { id: "hundred-first-match", region: "global", text: "The Hundred's first-ever men's match, Oval Invincibles against Manchester Originals, was played here.", answer: "The Oval, London", when: "22 July 2021", lat: 51.4837, lng: -0.115, scaleKm: 500, story: "The women's competition had opened at the same ground the night before.", source: W("The_Hundred_(cricket)") },
];

// Curated dailies: 3 India + 2 global, easy to hard. Unscheduled questions feed Practice.
export const SCHEDULE: string[][] = [
  ["dhoni-2011-winning-six", "mccullum-first-ipl-match", "bumrah-birthplace", "warne-ball-of-the-century", "yuvraj-six-sixes"],
  ["kapil-1983-final", "dhoni-birthplace", "laxman-281", "stokes-headingley", "lara-400"],
  ["kohli-birthplace", "kumble-10-wickets", "sachin-first-odi-200", "the-438-game", "first-ever-test"],
  ["t20wc-2024-final", "wc-2023-final", "tied-test-1986", "sachin-desert-storm", "murali-800"],
  ["india-women-wc-2025", "gabba-2021", "mithali-birthplace", "india-36-all-out", "mccullum-302"],
  ["sachin-birthplace", "shoaib-birthplace", "wc-1999-semi-tie", "sachin-98-centurion", "sl-952"],
  ["wc-2019-final", "wasim-birthplace", "bradman-bowral", "eng-481", "rashid-birthplace"],
];
